// Author Nick R/IshB//
//Created 3-9-2021//
//License: Public Domain//



// define my function as sortingHatLength, (str) is the parameter: aka this function is doing something with a string
function sortingHatLength(str) {

  //declare len as the lentgh of string
  var len = str.length;


//variable mod is that length/4

  var mod = len%4;


// MOD WILL RETURN A VALUE BETWEEN 0-3, WHEN IT DOES THAT, RETURN A Hogwarts HOUSE ACCORDINGLY//


//DO SO BY CHECKING IF THE VALUE RETURNED IS = 0, ELSE IF 1,2,3. AKA: IF VALUE RETURNED IS =  0 RETURN GRYFF. IF ITS NOT ZERO, CHECK IF ITS = 1, IF SO RETURN "HUFFL.", IF ITS NOT 1... REPEAT TIL 3
  if (mod == 0){
    return "Gryffindor"
  }

  else if (mod == 1){
    return "Hufflepuff"
  }
  else if (mod == 2){
    return "Ravenclaw"
  }
  else if (mod == 3){
    return "Slytherin"
  }
}

//DECLARE VARIABLE myButton TO BE = THE ELEMENT IN MY HTML DOCUMENT WITH THE ID NAME MY-BUTTON"

var myButton = document.getElementById("my-button");

myButton.addEventListener("click", function() {
  // REPEAT PROCESS FOR VAR name, VAR house
  var name = document.getElementById("input").value;

  var house = sortingHatLength(name);
  // DECLARE newText TO BE A PARAGRAPH WITH THE TEXT in quotes plus the variable house
  var newText = "<p> The Sorting Hat has placed you into " + house + "</p>";
  //PLACE TEXT GENERATED BY VAR newText INSIDE THE ELEMENT IN MY HTML DOC WITH THE ID NAME OUTPUT
  document.getElementById("output").innerHTML = newText;

})
